version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    # simple! without user nor pwd! 
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: pwd
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
